### ISSUE TITLE
Cannot use with multiple plans

### ISSUE THREAD

**Issue by supungs** [rinvex/laravel-subscriptions#115] opened 2020-09-13 12:02 UTC
Is this package only useful when there's only a single plan? When multiple plans have the same feature, they get different slugs, which makes it impossible to check whether a user has a permission or not.

**Comment by julienarcin** [comment] 2020-09-24 12:16
Same 
Duplicate of #101

**Comment by andrewl94** [comment] 2020-11-08 16:32
Hi!
The linked duplicate is inconclusive and the @supungs got no real answer. I'll submit my message here since it still open.

Reading #101 The same applies to my perception. An project where we have the plans Tier 1, Tier 2 and Tier 3, where all of them have access to "Feature 1", but only Tier 2 and Tier 3 have "Feature 2", today we need to rely on the Name of the feature, not the Unique Identifiers, and the features are duplicated. This is a bad practice, but necessary on the current model of the package today.

Why a feature is directly linked to an plan? Is there any discussion or roadmap to allow an n:n relation between Plans and Features?

**Comment by mirza4027** [comment] 2021-07-26 14:12
public function getFeatureLimit($subscriptions, $featureType)
{
$limit = 0;
if(!empty($subscriptions)) {

  foreach ($subscriptions as $subscription) {

    $plan = app('rinvex.subscriptions.plan')->find($subscription->plan_id);
    $hasFeatureType = $plan->features()->where('slug', $featureType . '_' . $plan->slug)->get();
    if(!empty($hasFeatureType)) {
      $limit += $subscription->getFeatureValue($featureType . '_' . $plan->slug);
    } else {
      continue;
    }
  }
}

return $limit;
}

My workaround for this is currently where I check multiple plans having the same feature. Concatenated the feature type with the plan slug, which is basically starting the plan feature name with the common prefix. In your case your every plan needs to have a feature starting with 'email_notifications_'.$plan_slug

**Comment by Omranic** [comment] 2021-09-27 10:22
This is considered for a future release.

PRs are most welcome to add this feature 😉

**Closed by Omranic** 2021-09-27 10:22 UTC
